backend:
  name: github
  repo: OmrJCo/price-webapp
  branch: main

media_folder: "assets"
public_folder: "/price-webapp/assets"

collections:
  - name: "categories"
    label: "Categories"
    files:
      - name: "all"
        label: "All Categories"
        file: "categories.json"
        format: "json"
        fields:
          - label: "Site Title"
            name: "siteTitle"
            widget: "string"
            required: false

          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Title (EN)", name: "titleEN", widget: "string" }
              - { label: "Title (TH)", name: "titleTH", widget: "string" }
              - { label: "Image", name: "image", widget: "string", required: false }
              - { label: "PDF Path", name: "pdf", widget: "string", required: false }
