backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

site_url: https://moonlit-halva-d42472.netlify.app
display_url: https://moonlit-halva-d42472.netlify.app

collections:
  - name: "categories_config"
    label: "Categories"
    files:
      - name: "categories"
        label: "All Categories"
        file: "categories.json"
        format: "json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string", required: false }
          - { label: "Site Subtitle", name: "siteSubtitle", widget: "string", required: false }
          - { label: "Cover Image", name: "coverImage", widget: "string", required: false }
          - { label: "Cover Headline", name: "coverHeadline", widget: "string", required: false }
          - { label: "Cover Subtext", name: "coverSubtext", widget: "string", required: false }

          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Title (EN)", name: "titleEN", widget: "string" }
              - { label: "Title (TH)", name: "titleTH", widget: "string" }
              - { label: "Image", name: "image", widget: "string", required: false }
              - { label: "PDF Path", name: "pdf", widget: "string" }
