backend:
  name: github
  repo: runmaster/repo-name
  branch: main
  use_graphql: true

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "categories_config"
    label: "Categories"
    files:
      - file: "categories.json"
        label: "All Categories"
        name: "all"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            summary: "{{fields.titleEN}} — {{fields.titleTH}}"
            fields:
              - { label: "Title (EN)", name: "titleEN", widget: "string" }
              - { label: "Title (TH)", name: "titleTH", widget: "string" }
              - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "PDF Path", name: "pdf", widget: "string", hint: "เช่น pdf/battery.pdf" }
